# -*- coding: utf-8 -*-
"""CNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNpMu7arJpqepd6kopKIgL567Hwnk3Gl
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
from torch.utils.data import DataLoader
import torchvision.datasets as datasets
import torchvision.transforms as transforms
import torchvision.models as models
from torch.optim.lr_scheduler import StepLR

"""Set device"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

"""extract the zip"""

import zipfile
import os

# Set the path to the ZIP file
zip_filename = "/content/state_classification_dataset.zip"

# Define the extraction path
extract_path = "/content/images_folder"
os.makedirs(extract_path, exist_ok=True)

# Extract the ZIP file
with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# Verify the extracted files
print("Extracted files:", os.listdir(extract_path))

"""Resizing images"""

transform = transforms.Compose([
    transforms.Resize((224, 224)),  # Standard ImageNet picture size
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]) # Use ImageNet mean and std
])

"""Loading the data set"""

train_dataset = datasets.ImageFolder(root='/content/images_folder/state_dataset/train', transform=transform) #loads training imagaes
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True) #loads data in batches of 32 being shuffled
val_dataset = datasets.ImageFolder(root='/content/images_folder/state_dataset/valid', transform=transform) #loads validiation imagaes
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=True) #loads data in batches of 32 being shuffled

"""Baseline model (VGG)"""

num_classes = len(train_dataset.classes)

# Load a pretrained VGG16 model:
baseline_model = models.vgg16(pretrained=True)

# Freeze all layers except the classifier
for param in baseline_model.features.parameters():
    param.requires_grad = False

# Modify the last layer for VGG16:
num_ftrs = baseline_model.classifier[6].in_features
baseline_model.classifier[6] = nn.Linear(num_ftrs, num_classes)

# Move model to device:
baseline_model = baseline_model.to(device)

"""CNN model"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import models

# Squeeze-and-Excitation (SE) Block
class SEBlock(nn.Module):
    def __init__(self, in_channels, reduction=16):
        super(SEBlock, self).__init__()
        self.pool = nn.AdaptiveAvgPool2d(1)
        self.fc = nn.Sequential(
            nn.Linear(in_channels, in_channels // reduction),
            nn.SiLU(inplace=True),
            nn.Linear(in_channels // reduction, in_channels),
            nn.Sigmoid()
        )

    def forward(self, x):
        b, c, _, _ = x.size()
        y = self.pool(x).view(b, c)
        y = self.fc(y).view(b, c, 1, 1)
        return x * y

# Hybrid CNN Model with ResNet34 base
class HybridCNN(nn.Module):
    def __init__(self, num_classes, fine_tune_resnet=False):
        super(HybridCNN, self).__init__()

        # Load pretrained ResNet34
        resnet34 = models.resnet34(pretrained=True)

        # Keep layers up to layer3
        self.resnet_base = nn.Sequential(
            resnet34.conv1,
            resnet34.bn1,
            resnet34.relu,
            resnet34.maxpool,
            resnet34.layer1,
            resnet34.layer2,
            resnet34.layer3
        )

        # Optionally fine-tune some ResNet layers
        for param in self.resnet_base.parameters():
            param.requires_grad = fine_tune_resnet

        # Custom conv layers with SE and SiLU
        self.custom_conv = nn.Sequential(
            nn.Conv2d(256, 256, kernel_size=3, padding=1),
            nn.BatchNorm2d(256),
            nn.SiLU(),
            SEBlock(256),
            nn.MaxPool2d(2),

            nn.Conv2d(256, 512, kernel_size=3, padding=1),
            nn.BatchNorm2d(512),
            nn.SiLU(),
            SEBlock(512),
            nn.AdaptiveAvgPool2d((1, 1))
        )

        # Classifier
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(512, 256),
            nn.SiLU(),
            nn.Dropout(0.5),
            nn.Linear(256, num_classes)
        )

        # Initialize custom layers
        self.custom_conv.apply(self._init_weights)
        self.classifier.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Conv2d) or isinstance(m, nn.Linear):
            nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
            if m.bias is not None:
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        x = self.resnet_base(x)
        x = self.custom_conv(x)
        x = self.classifier(x)
        return x

"""Hyperparameters"""

learning_rate = 0.01
num_epochs = 15 #should be increased later

"""Initialize model"""

model = HybridCNN(num_classes=num_classes).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)
scheduler = StepLR(optimizer, step_size=4, gamma=0.1)

"""Training loop and plot of loss"""

import matplotlib.pyplot as plt

# Initialize lists to store loss across all epochs
epoch_losses = []
baseline_epoch_losses = []
val_losses = []  # Add list for validation losses (custom model)
baseline_val_losses = []  # Add list for validation losses (baseline model)
epochs = []

# Training loop for custom model
for epoch in range(num_epochs):
    print(f"Epoch {epoch+1}/{num_epochs}")

    running_loss = 0.0  # Accumulate loss for the epoch

    for batch_idx, (data, targets) in enumerate(train_loader):
        data = data.to(device)
        targets = targets.to(device)

        # Forward
        scores = model(data)
        loss = criterion(scores, targets)

        # Backward
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    epoch_loss = running_loss / len(train_loader)  # Calculate average epoch loss
    epoch_losses.append(epoch_loss)
    epochs.append(epoch + 1)  # Store epoch number
    print(f"Training Loss: {epoch_loss:.4f}")  # Print training loss

    scheduler.step()

    # Calculate validation loss for custom model
    model.eval()  # Set to evaluation mode
    with torch.no_grad():
        val_loss = 0.0
        for batch_idx, (data, targets) in enumerate(val_loader):
            data = data.to(device)
            targets = targets.to(device)
            outputs = model(data)
            loss = criterion(outputs, targets)
            val_loss += loss.item()
    val_losses.append(val_loss / len(val_loader))
    print(f"Validation Loss: {val_loss / len(val_loader):.4f}")  # Print validation loss
    model.train()  # Set back to training mode

# Training loop for baseline VGG model
baseline_optimizer = optim.Adam(baseline_model.parameters(), lr=learning_rate)  # Example

for epoch in range(num_epochs):
    print(f"Epoch {epoch+1}/{num_epochs} (Baseline)")

    running_loss_baseline = 0.0

    for batch_idx, (data, targets) in enumerate(train_loader):
        data = data.to(device)
        targets = targets.to(device)

        # Forward pass for baseline model
        scores = baseline_model(data)
        loss = criterion(scores, targets)

        # Backward pass and optimization for baseline model
        baseline_optimizer.zero_grad()
        loss.backward()
        baseline_optimizer.step()

        running_loss_baseline += loss.item()

    epoch_loss_baseline = running_loss_baseline / len(train_loader)
    baseline_epoch_losses.append(epoch_loss_baseline)
    print(f"Baseline Training Loss: {epoch_loss_baseline:.4f}")

    # Calculate validation loss for baseline model
    baseline_model.eval()  # Set to evaluation mode
    with torch.no_grad():
        val_loss_baseline = 0.0
        for batch_idx, (data, targets) in enumerate(val_loader):
            data = data.to(device)
            targets = targets.to(device)
            outputs = baseline_model(data)
            loss = criterion(outputs, targets)
            val_loss_baseline += loss.item()
    baseline_val_losses.append(val_loss_baseline / len(val_loader))
    print(f"Baseline Validation Loss: {val_loss_baseline / len(val_loader):.4f}")
    baseline_model.train()  # Set back to training mode

# Plotting the losses for the custom model
plt.figure(figsize=(12, 6))
plt.plot(epochs, epoch_losses, label="Training Loss", color='blue')
plt.plot(epochs, val_losses, label="Validation Loss", color='red')
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Custom Model: Training and Validation Loss")
plt.legend()
plt.show()

# Plotting the losses for the baseline VGG model
plt.figure(figsize=(12, 6))
plt.plot(epochs, baseline_epoch_losses, label="Training Loss", color='blue')
plt.plot(epochs, baseline_val_losses, label="Validation Loss", color='red')
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Baseline VGG Model: Training and Validation Loss")
plt.legend()
plt.show()

print(f"Final Loss: {epoch_losses[-1]:.4f}")  # Print final batch loss
print(f"Final Baseline Loss: {baseline_epoch_losses[-1]:.4f}")
torch.save(model.state_dict(), "model.pth")

"""Check accuracy"""

def check_accuracy(loader, model):
    num_correct = 0
    num_samples = 0
    model.eval()

    with torch.no_grad():
        for x, y in loader:
            x = x.to(device)
            y = y.to(device)

            scores = model(x)
            _, predictions = scores.max(1)
            num_correct += (predictions == y).sum()
            num_samples += predictions.size(0)

        accuracy = float(num_correct) / float(num_samples) * 100
        print(f"Got {num_correct} / {num_samples} with accuracy {accuracy:.2f}%")

    model.train()

"""
Run accuracy check based on unseen images"""

check_accuracy(val_loader, model)
check_accuracy(val_loader, baseline_model)

import random
import numpy as np

def show_random_images(dataset, class_names, num_images=5):
    fig, axes = plt.subplots(1, num_images, figsize=(15, 5))

    for i in range(num_images):
        idx = random.randint(0, len(dataset) - 1)  # Select a random index
        img, label = dataset[idx]  # Get image and label

        # Unnormalize the image
        mean = np.array([0.485, 0.456, 0.406]) #your mean used in transform
        std = np.array([0.229, 0.224, 0.225])  #your std used in transform
        img = img.numpy() #convert tensor to numpy array
        img = std[:, None, None] * img + mean[:, None, None] #apply the unnormalization formula
        img = np.clip(img, 0, 1) #clip any values still outside the valid range.
        img = img.transpose((1, 2, 0))  # Convert to (H, W, C) format for displaying

        axes[i].imshow(img)  # Unnormalized image
        axes[i].set_title(class_names[label])  # Set title as class name
        axes[i].axis("off")  # Hide axes

    plt.show()

# Call function
show_random_images(val_dataset, val_dataset.classes)